# Generated by Django 2.2.7 on 2019-11-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fio',
            field=models.CharField(blank=True, default='не указано', max_length=50, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobby',
            field=models.CharField(blank=True, default='не указано', max_length=50, null=True, verbose_name='Хобби'),
        ),
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.TextField(blank=True, default='не указано', null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isOfferRent',
            field=models.BooleanField(default=False, verbose_name='Арендадатель?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, default='не указано', max_length=50, null=True, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='study',
            field=models.CharField(blank=True, default='не указано', max_length=50, null=True, verbose_name='Образование'),
        ),
    ]
