# Generated by Django 2.2.7 on 2019-11-24 12:35

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение')),
                ('boolValue', models.BooleanField(null=True, verbose_name='Значение Да/Нет')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('short_description', models.CharField(max_length=100, null=True, verbose_name='Краткое описание (100 символов)')),
                ('image', models.ImageField(blank=True, upload_to='house_img/', verbose_name='Изображение превью )')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Описание помещения')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активно?')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
            },
        ),
        migrations.CreateModel(
            name='HouseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория помещения')),
            ],
            options={
                'verbose_name': 'Категория помещения',
                'verbose_name_plural': 'Категории помещений',
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег к новости')),
            ],
            options={
                'verbose_name': 'Тег к новости',
                'verbose_name_plural': 'Теги к новости',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='blog_img/', verbose_name='Изображение превью')),
                ('short_description', models.CharField(max_length=100, verbose_name='Краткое описание (100 символов)')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Статья')),
                ('isShowAtIndex', models.BooleanField(default=True, verbose_name='Отображать на главной?')),
                ('tags', models.ManyToManyField(related_name='tags', to='pages.NewsTag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='HousePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='house_img/', verbose_name='Изображение)')),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.House', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Изображение помещения',
                'verbose_name_plural': 'Изображения помещений',
            },
        ),
        migrations.AddField(
            model_name='house',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.HouseCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='house',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='house',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Town', verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='CategoryFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фильтр помещения')),
                ('house', models.ManyToManyField(blank=True, null=True, to='pages.HouseCategory', verbose_name='Помещение')),
                ('val', models.ManyToManyField(blank=True, null=True, to='pages.FilterValue')),
            ],
            options={
                'verbose_name': 'Фильтр помещения',
                'verbose_name_plural': 'Фильтры помещений',
            },
        ),
    ]
