# Generated by Django 2.2.7 on 2019-11-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryfilter',
            name='house',
        ),
        migrations.RemoveField(
            model_name='categoryfilter',
            name='val',
        ),
        migrations.AddField(
            model_name='categoryfilter',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.HouseCategory', verbose_name='Помещение'),
        ),
    ]
