# Generated by Django 2.2.7 on 2019-11-24 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191124_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryfilter',
            name='values',
            field=models.ManyToManyField(blank=True, null=True, to='pages.FilterValue'),
        ),
        migrations.AddField(
            model_name='filtervalue',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.House', verbose_name='Помещение'),
        ),
    ]
