# Generated by Django 2.2.7 on 2019-11-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20191124_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryfilter',
            name='values',
        ),
    ]
