# Generated by Django 2.2.7 on 2019-11-27 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0005_delete_filtervalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfilter',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.HouseCategory', verbose_name='Для категории помещения'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.House', verbose_name='Помещение')),
            ],
        ),
    ]
