# Generated by Django 2.2.7 on 2019-11-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20191127_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='news',
            name='imageBig',
            field=models.ImageField(blank=True, upload_to='blog_img/', verbose_name='Изображение на страницу'),
        ),
    ]
