# Generated by Django 2.2.7 on 2019-12-08 12:11

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20191128_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='rentTime',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
