# Generated by Django 2.2.7 on 2019-12-08 12:55

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_rent_renttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalRentTime', jsonfield.fields.JSONField(blank=True, null=True)),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.House', verbose_name='Помещение')),
            ],
        ),
    ]
