# Generated by Django 2.2.7 on 2019-12-15 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0011_globalrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('messageFrom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messageFrom', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('messageTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messageTo', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
        ),
    ]
