# Generated by Django 2.2.7 on 2019-12-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
    ]
