# Generated by Django 2.2.7 on 2019-11-24 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0004_remove_categoryfilter_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение')),
                ('boolValue', models.BooleanField(null=True, verbose_name='Значение Да/Нет')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='pages.House', verbose_name='Помещение')),
            ],
        ),
    ]
